# Generated by Django 5.2.16 on 2026-07-27 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.PositiveIntegerField(default=0)),
                ('avg_focus_score', models.FloatField(default=0.0)),
                ('total_distractions', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('telemetry_points_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical')], default='good', max_length=20)),
                ('status_key', models.CharField(default='good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusTelemetryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='progress.focussession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
