# Generated by Django 5.2.16 on 2026-07-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_page_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='page_path',
            field=models.CharField(blank=True, default='', help_text='مسار الصفحة عند بدء الشات (يفيد الأسئلة عن التنقل في المنصة).', max_length=512),
        ),
    ]
