# Generated by Django 5.2.16 on 2026-07-27 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('avg_focus_score', models.FloatField(default=0.0)),
                ('total_distractions', models.PositiveIntegerField(default=0)),
                ('telemetry_points_count', models.PositiveIntegerField(default=0)),
                ('status_key', models.CharField(default='good', max_length=20)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringTelemetryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('score', models.FloatField(default=0.0)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='monitoring.monitoringsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
