# Generated by Django 5.2.14 on 2026-05-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order_rank', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(default=1)),
                ('title_ar', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('summary_ar', models.TextField(blank=True)),
                ('summary_en', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('eng_query', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(default='📦', max_length=10)),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50)),
                ('order_num', models.PositiveIntegerField(default=1)),
                ('title_ar', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('skill_type', models.CharField(choices=[('concept', 'Concept'), ('tool', 'Tool'), ('practice', 'Practice')], default='concept', max_length=20)),
                ('resources', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='roadmaps.module')),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=20)),
                ('goal_ar', models.TextField(blank=True)),
                ('goal_en', models.TextField(blank=True)),
                ('duration_months', models.PositiveIntegerField(default=3)),
                ('projects_needed', models.PositiveIntegerField(default=0)),
                ('can_do_ar', models.JSONField(blank=True, default=list)),
                ('can_do_en', models.JSONField(blank=True, default=list)),
                ('ready_when_ar', models.TextField(blank=True)),
                ('ready_when_en', models.TextField(blank=True)),
                ('job_requirements', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='roadmaps.field')),
            ],
            options={
                'ordering': ['field', 'career_level'],
                'unique_together': {('field', 'career_level')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50)),
                ('order_num', models.PositiveIntegerField(default=1)),
                ('title_ar', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('estimated_days', models.PositiveIntegerField(default=3)),
                ('skills_covered', models.JSONField(blank=True, default=list)),
                ('example_repo', models.URLField(blank=True, max_length=500)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('bonus_features', models.JSONField(blank=True, default=list)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='roadmaps.track')),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ar', 'ar'), ('en', 'en')], max_length=5)),
                ('youtube_url', models.URLField(max_length=500)),
                ('playlist_id', models.CharField(blank=True, max_length=50)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('verified_year', models.PositiveIntegerField(blank=True, null=True)),
                ('approx_views', models.BigIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='roadmaps.track')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='roadmaps.track'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('track', 'order_num')},
        ),
    ]
