# Generated by Django 5.2.14 on 2026-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='books_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum books to read before completing this level'),
        ),
        migrations.AddField(
            model_name='track',
            name='projects_to_advance',
            field=models.PositiveIntegerField(default=0, help_text='Projects needed to unlock next level (e.g. 40 for Junior→Mid)'),
        ),
    ]
