# Generated by Django 5.2.14 on 2026-05-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_track_books_required_track_projects_to_advance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['order_num', 'id']},
        ),
        migrations.AddField(
            model_name='playlist',
            name='order_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='role_label',
            field=models.CharField(blank=True, help_text='e.g. Core course, Projects', max_length=80),
        ),
        migrations.AddField(
            model_name='playlist',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='lang',
            field=models.CharField(choices=[('ar', 'ar'), ('en', 'en')], default='en', max_length=5),
        ),
    ]
